[tool.pytest.ini_options]
pythonpath = [
    ".",
    "../../opn-intelligence/app_services_parent"
]
testpaths = ["app_services_parent/shipment/tests"]
python_files = ["test_*.py"]
addopts = "-v --cov=app_services_parent.shipment.app --cov-report=html --cov-report=term-missing"
